### ISSUE TITLE
Use Hardlinks to manage version

### ISSUE THREAD

**Issue by diamondo25** [DaWolf85/GTAVAutoPatcher#2]
If you use hardlinks, you can easily swap the files and folders. Note that this is pretty much an alias of the path, so use with caution.

**Comment by DaWolf85** [comment]
Closing as this project cannot downgrade GTA V due to Rockstar updates (and can't be updated to do so either). All downgrades should now be done using [Project 1.27](https://github.com/TwosHusbandS/Project-127).
